/**
 * High-grade expanded smartphone catalog with authentic specs,
 * multiple variants, hex swatches, and verified image links.
 * Works seamlessly both standalone (embedded store) and in PostgreSQL.
 */

const PRODUCTS = [
  // ================= APPLE =================
  {
    id: 1,
    slug: 'iphone-17-pro',
    name: 'iPhone 17 Pro',
    brand: 'Apple',
    tagline: 'Titanium precision with next-gen A19 Pro neural engine.',
    description: "Apple's flagship Pro smartphone featuring Grade 5 titanium, A19 Pro chip with hardware ray tracing, 48MP triple camera system with 5x telephoto optical zoom, and ceramic shield protection.",
    category: 'flagship',
    rating: 4.9,
    reviewsCount: 342,
    specs: {
      display: '6.3-inch Super Retina XDR OLED, 120Hz ProMotion, 2500 nits peak',
      processor: 'Apple A19 Pro (3nm) with 6-core GPU & 16-core Neural Engine',
      camera: 'Triple 48MP Main + 48MP Ultra-Wide + 48MP 5x Periscope Telephoto',
      battery: '3650 mAh, 30W wired, 25W MagSafe wireless charging',
      os: 'iOS 19 with Apple Intelligence',
      security: 'Face ID biometric authentication',
      weight: '188g',
    },
    variants: [
      {
        id: 101,
        label: '256GB / Deep Blue',
        storage: '256GB',
        color: 'Deep Blue',
        colorHex: '#1E293B',
        mrp: 134900,
        sellingPrice: 127400,
        imageUrl: 'https://images.unsplash.com/photo-1695048133142-1a20484d2569?auto=format&fit=crop&w=1000&q=85',
        isDefault: true,
        stockStatus: 'in_stock',
        emiLadder: [
          { tenureMonths: 3, annualInterestRate: 0, cashbackAmount: 7500, isRecommended: false },
          { tenureMonths: 6, annualInterestRate: 0, cashbackAmount: 7500, isRecommended: false },
          { tenureMonths: 12, annualInterestRate: 0, cashbackAmount: 7500, isRecommended: true },
          { tenureMonths: 24, annualInterestRate: 0, cashbackAmount: 7500, isRecommended: false },
          { tenureMonths: 36, annualInterestRate: 10.5, cashbackAmount: 7500, isRecommended: false },
          { tenureMonths: 48, annualInterestRate: 10.5, cashbackAmount: 7500, isRecommended: false },
        ],
      },
      {
        id: 102,
        label: '256GB / Cosmic Orange',
        storage: '256GB',
        color: 'Cosmic Orange',
        colorHex: '#C96A3C',
        mrp: 134900,
        sellingPrice: 129900,
        imageUrl: 'https://images.unsplash.com/photo-1695048132966-4b6c30f0e02b?auto=format&fit=crop&w=1000&q=85',
        isDefault: false,
        stockStatus: 'in_stock',
        emiLadder: [
          { tenureMonths: 3, annualInterestRate: 0, cashbackAmount: 7000, isRecommended: false },
          { tenureMonths: 6, annualInterestRate: 0, cashbackAmount: 7000, isRecommended: false },
          { tenureMonths: 12, annualInterestRate: 0, cashbackAmount: 7000, isRecommended: true },
          { tenureMonths: 24, annualInterestRate: 0, cashbackAmount: 7000, isRecommended: false },
          { tenureMonths: 36, annualInterestRate: 10.5, cashbackAmount: 7000, isRecommended: false },
        ],
      },
      {
        id: 103,
        label: '512GB / Natural Titanium',
        storage: '512GB',
        color: 'Natural Titanium',
        colorHex: '#9E978E',
        mrp: 154900,
        sellingPrice: 147400,
        imageUrl: 'https://images.unsplash.com/photo-1592750475338-74b7b21085ab?auto=format&fit=crop&w=1000&q=85',
        isDefault: false,
        stockStatus: 'in_stock',
        emiLadder: [
          { tenureMonths: 6, annualInterestRate: 0, cashbackAmount: 8500, isRecommended: false },
          { tenureMonths: 12, annualInterestRate: 0, cashbackAmount: 8500, isRecommended: true },
          { tenureMonths: 24, annualInterestRate: 0, cashbackAmount: 8500, isRecommended: false },
          { tenureMonths: 36, annualInterestRate: 10.5, cashbackAmount: 8500, isRecommended: false },
        ],
      },
    ],
  },
  {
    id: 2,
    slug: 'iphone-16-pro-max',
    name: 'iPhone 16 Pro Max',
    brand: 'Apple',
    tagline: 'The ultimate iPhone with expansive 6.9-inch display & Camera Control.',
    description: 'Featuring an aerospace titanium body, thin borders, A18 Pro silicon, Camera Control tactile button, and 4K 120 fps Dolby Vision video recording.',
    category: 'flagship',
    rating: 4.95,
    reviewsCount: 512,
    specs: {
      display: '6.9-inch Super Retina XDR OLED, 120Hz ProMotion, 2000 nits peak',
      processor: 'Apple A18 Pro (3nm second-gen)',
      camera: '48MP Fusion + 48MP Ultra Wide + 12MP 5x Telephoto',
      battery: '4685 mAh, all-day 33hr video playback',
      os: 'iOS 18 / iOS 19 upgradable',
      security: 'Face ID & Camera Control capacitive sensor',
      weight: '227g',
    },
    variants: [
      {
        id: 201,
        label: '256GB / Desert Titanium',
        storage: '256GB',
        color: 'Desert Titanium',
        colorHex: '#C5A992',
        mrp: 144900,
        sellingPrice: 139900,
        imageUrl: 'https://images.unsplash.com/photo-1510557880182-3d4d3cba35a5?auto=format&fit=crop&w=1000&q=85',
        isDefault: true,
        stockStatus: 'in_stock',
        emiLadder: [
          { tenureMonths: 3, annualInterestRate: 0, cashbackAmount: 8000, isRecommended: false },
          { tenureMonths: 6, annualInterestRate: 0, cashbackAmount: 8000, isRecommended: false },
          { tenureMonths: 12, annualInterestRate: 0, cashbackAmount: 8000, isRecommended: true },
          { tenureMonths: 24, annualInterestRate: 0, cashbackAmount: 8000, isRecommended: false },
          { tenureMonths: 36, annualInterestRate: 10.5, cashbackAmount: 8000, isRecommended: false },
        ],
      },
      {
        id: 202,
        label: '512GB / Black Titanium',
        storage: '512GB',
        color: 'Black Titanium',
        colorHex: '#1F2428',
        mrp: 164900,
        sellingPrice: 159900,
        imageUrl: 'https://images.unsplash.com/photo-1511707171634-5f897ff02aa9?auto=format&fit=crop&w=1000&q=85',
        isDefault: false,
        stockStatus: 'in_stock',
        emiLadder: [
          { tenureMonths: 6, annualInterestRate: 0, cashbackAmount: 9000, isRecommended: false },
          { tenureMonths: 12, annualInterestRate: 0, cashbackAmount: 9000, isRecommended: true },
          { tenureMonths: 24, annualInterestRate: 0, cashbackAmount: 9000, isRecommended: false },
        ],
      },
    ],
  },
  {
    id: 3,
    slug: 'iphone-16',
    name: 'iPhone 16',
    brand: 'Apple',
    tagline: 'Colour-infused glass with A18 chip and Camera Control.',
    description: 'Vibrant color-infused back glass, Action button, dual 48MP Fusion camera system with macro photography, and blazing fast A18 chip.',
    category: 'flagship',
    rating: 4.8,
    reviewsCount: 220,
    specs: {
      display: '6.1-inch Super Retina XDR OLED, 2000 nits peak brightness',
      processor: 'Apple A18 (3nm) with Apple Intelligence',
      camera: '48MP Fusion main + 12MP Ultra Wide with autofocus',
      battery: '3561 mAh with fast 25W MagSafe',
      os: 'iOS 18',
      security: 'Face ID',
      weight: '170g',
    },
    variants: [
      {
        id: 301,
        label: '128GB / Ultramarine',
        storage: '128GB',
        color: 'Ultramarine',
        colorHex: '#3B60E4',
        mrp: 79900,
        sellingPrice: 74900,
        imageUrl: 'https://images.unsplash.com/photo-1591337676887-a217a6970a8a?auto=format&fit=crop&w=1000&q=85',
        isDefault: true,
        stockStatus: 'in_stock',
        emiLadder: [
          { tenureMonths: 3, annualInterestRate: 0, cashbackAmount: 4000, isRecommended: false },
          { tenureMonths: 6, annualInterestRate: 0, cashbackAmount: 4000, isRecommended: false },
          { tenureMonths: 12, annualInterestRate: 0, cashbackAmount: 4000, isRecommended: true },
          { tenureMonths: 24, annualInterestRate: 0, cashbackAmount: 4000, isRecommended: false },
        ],
      },
      {
        id: 302,
        label: '256GB / Teal',
        storage: '256GB',
        color: 'Teal',
        colorHex: '#4E938A',
        mrp: 89900,
        sellingPrice: 84900,
        imageUrl: 'https://images.unsplash.com/photo-1575695342320-d2d2d2f9b73f?auto=format&fit=crop&w=1000&q=85',
        isDefault: false,
        stockStatus: 'in_stock',
        emiLadder: [
          { tenureMonths: 6, annualInterestRate: 0, cashbackAmount: 4500, isRecommended: false },
          { tenureMonths: 12, annualInterestRate: 0, cashbackAmount: 4500, isRecommended: true },
          { tenureMonths: 24, annualInterestRate: 0, cashbackAmount: 4500, isRecommended: false },
        ],
      },
    ],
  },

  // ================= SAMSUNG =================
  {
    id: 4,
    slug: 'samsung-galaxy-s24-ultra',
    name: 'Samsung Galaxy S24 Ultra',
    brand: 'Samsung',
    tagline: 'Titanium durability with built-in S Pen & 200MP Quad Tele System.',
    description: "Samsung's crowning Galaxy flagship featuring flat Corning Gorilla Armor, integrated S Pen, Galaxy AI suite (Circle to Search, Live Translate), and Snapdragon 8 Gen 3 for Galaxy.",
    category: 'flagship',
    rating: 4.9,
    reviewsCount: 460,
    specs: {
      display: '6.8-inch Dynamic AMOLED 2X, QHD+, 1-120Hz LTPO, 2600 nits, Anti-reflective',
      processor: 'Snapdragon 8 Gen 3 for Galaxy (4nm)',
      camera: '200MP Main + 50MP 5x Telephoto + 10MP 3x Telephoto + 12MP Ultra-wide',
      battery: '5000 mAh, 45W wired, 15W wireless',
      os: 'One UI 6.1 with 7 years of Android OS updates',
      security: 'Ultrasonic In-display Fingerprint & Knox Vault',
      weight: '232g',
    },
    variants: [
      {
        id: 401,
        label: '256GB / Titanium Black',
        storage: '256GB',
        color: 'Titanium Black',
        colorHex: '#1B1B1D',
        mrp: 129999,
        sellingPrice: 114999,
        imageUrl: 'https://images.unsplash.com/photo-1610945265064-0e34e5519bbf?auto=format&fit=crop&w=1000&q=85',
        isDefault: true,
        stockStatus: 'in_stock',
        emiLadder: [
          { tenureMonths: 3, annualInterestRate: 0, cashbackAmount: 6000, isRecommended: false },
          { tenureMonths: 6, annualInterestRate: 0, cashbackAmount: 6000, isRecommended: false },
          { tenureMonths: 12, annualInterestRate: 0, cashbackAmount: 6000, isRecommended: true },
          { tenureMonths: 24, annualInterestRate: 0, cashbackAmount: 6000, isRecommended: false },
          { tenureMonths: 36, annualInterestRate: 10.5, cashbackAmount: 6000, isRecommended: false },
        ],
      },
      {
        id: 402,
        label: '256GB / Titanium Gray',
        storage: '256GB',
        color: 'Titanium Gray',
        colorHex: '#8A8D8F',
        mrp: 129999,
        sellingPrice: 116999,
        imageUrl: 'https://images.unsplash.com/photo-1580910051074-3eb694886505?auto=format&fit=crop&w=1000&q=85',
        isDefault: false,
        stockStatus: 'in_stock',
        emiLadder: [
          { tenureMonths: 6, annualInterestRate: 0, cashbackAmount: 6000, isRecommended: false },
          { tenureMonths: 12, annualInterestRate: 0, cashbackAmount: 6000, isRecommended: true },
          { tenureMonths: 24, annualInterestRate: 0, cashbackAmount: 6000, isRecommended: false },
        ],
      },
      {
        id: 403,
        label: '512GB / Titanium Violet',
        storage: '512GB',
        color: 'Titanium Violet',
        colorHex: '#4E445B',
        mrp: 144999,
        sellingPrice: 129999,
        imageUrl: 'https://images.unsplash.com/photo-1565849904461-04a58ad377e0?auto=format&fit=crop&w=1000&q=85',
        isDefault: false,
        stockStatus: 'in_stock',
        emiLadder: [
          { tenureMonths: 12, annualInterestRate: 0, cashbackAmount: 6500, isRecommended: true },
          { tenureMonths: 24, annualInterestRate: 0, cashbackAmount: 6500, isRecommended: false },
          { tenureMonths: 36, annualInterestRate: 10.5, cashbackAmount: 6500, isRecommended: false },
        ],
      },
    ],
  },
  {
    id: 5,
    slug: 'samsung-galaxy-z-fold-6',
    name: 'Samsung Galaxy Z Fold 6',
    brand: 'Samsung',
    tagline: 'Immersive 7.6-inch folding canvas with next-level multitasking.',
    description: 'Slimmer, lighter, and more durable dual-screen folding powerhouse. Enhanced Armor Aluminum hinge, S Pen fold edition support, and Dual-App multitasking.',
    category: 'foldable',
    rating: 4.85,
    reviewsCount: 180,
    specs: {
      display: 'Main: 7.6" Dynamic AMOLED 2X 120Hz; Cover: 6.3" Dynamic AMOLED 2X',
      processor: 'Snapdragon 8 Gen 3 for Galaxy',
      camera: '50MP Dual Pixel OIS + 10MP 3x Telephoto + 12MP Ultra Wide',
      battery: '4400 mAh with 25W fast charge',
      os: 'One UI 6.1.1 optimized for foldables',
      security: 'Side-mounted capacitive sensor & Knox',
      weight: '239g',
    },
    variants: [
      {
        id: 501,
        label: '256GB / Silver Shadow',
        storage: '256GB',
        color: 'Silver Shadow',
        colorHex: '#A3A8AF',
        mrp: 164999,
        sellingPrice: 154999,
        imageUrl: 'https://images.unsplash.com/photo-1584006682522-dc17d6c0d963?auto=format&fit=crop&w=1000&q=85',
        isDefault: true,
        stockStatus: 'in_stock',
        emiLadder: [
          { tenureMonths: 6, annualInterestRate: 0, cashbackAmount: 10000, isRecommended: false },
          { tenureMonths: 12, annualInterestRate: 0, cashbackAmount: 10000, isRecommended: true },
          { tenureMonths: 24, annualInterestRate: 0, cashbackAmount: 10000, isRecommended: false },
          { tenureMonths: 36, annualInterestRate: 10.5, cashbackAmount: 10000, isRecommended: false },
        ],
      },
      {
        id: 502,
        label: '512GB / Navy',
        storage: '512GB',
        color: 'Navy',
        colorHex: '#1E2C3E',
        mrp: 176999,
        sellingPrice: 166999,
        imageUrl: 'https://images.unsplash.com/photo-1546868871-7041f2a55e12?auto=format&fit=crop&w=1000&q=85',
        isDefault: false,
        stockStatus: 'in_stock',
        emiLadder: [
          { tenureMonths: 12, annualInterestRate: 0, cashbackAmount: 11000, isRecommended: true },
          { tenureMonths: 24, annualInterestRate: 0, cashbackAmount: 11000, isRecommended: false },
        ],
      },
    ],
  },

  // ================= GOOGLE PIXEL =================
  {
    id: 6,
    slug: 'google-pixel-9-pro-xl',
    name: 'Google Pixel 9 Pro XL',
    brand: 'Google',
    tagline: 'Engineered by Google with Gemini Nano & state-of-the-art computational cameras.',
    description: 'Sleek new camera bar design, polished metal frame, Super Actua display, Google Tensor G4 chip with 16GB RAM for advanced on-device multimodal AI.',
    category: 'flagship',
    rating: 4.88,
    reviewsCount: 310,
    specs: {
      display: '6.8-inch Super Actua LTPO OLED, 1-120Hz, up to 3000 nits peak',
      processor: 'Google Tensor G4 with Titan M2 security coprocessor',
      camera: '50MP Wide + 48MP Quad PD Ultrawide + 48MP 5x Telephoto with 30x Super Res Zoom',
      battery: '5060 mAh, 37W fast wired, 23W Pixel Stand wireless',
      os: 'Android 15 with 7 years of Pixel Drops and OS updates',
      security: 'Ultrasonic In-display & Face Unlock Class 3',
      weight: '221g',
    },
    variants: [
      {
        id: 601,
        label: '256GB / Obsidian',
        storage: '256GB',
        color: 'Obsidian',
        colorHex: '#202124',
        mrp: 124999,
        sellingPrice: 114999,
        imageUrl: 'https://images.unsplash.com/photo-1598327105666-5b89351aff97?auto=format&fit=crop&w=1000&q=85',
        isDefault: true,
        stockStatus: 'in_stock',
        emiLadder: [
          { tenureMonths: 3, annualInterestRate: 0, cashbackAmount: 6000, isRecommended: false },
          { tenureMonths: 6, annualInterestRate: 0, cashbackAmount: 6000, isRecommended: false },
          { tenureMonths: 12, annualInterestRate: 0, cashbackAmount: 6000, isRecommended: true },
          { tenureMonths: 24, annualInterestRate: 0, cashbackAmount: 6000, isRecommended: false },
        ],
      },
      {
        id: 602,
        label: '256GB / Porcelain',
        storage: '256GB',
        color: 'Porcelain',
        colorHex: '#F1EFE9',
        mrp: 124999,
        sellingPrice: 114999,
        imageUrl: 'https://images.unsplash.com/photo-1585060544812-6b45742d762f?auto=format&fit=crop&w=1000&q=85',
        isDefault: false,
        stockStatus: 'in_stock',
        emiLadder: [
          { tenureMonths: 6, annualInterestRate: 0, cashbackAmount: 6000, isRecommended: false },
          { tenureMonths: 12, annualInterestRate: 0, cashbackAmount: 6000, isRecommended: true },
          { tenureMonths: 24, annualInterestRate: 0, cashbackAmount: 6000, isRecommended: false },
        ],
      },
      {
        id: 603,
        label: '512GB / Hazel',
        storage: '512GB',
        color: 'Hazel',
        colorHex: '#58615A',
        mrp: 139999,
        sellingPrice: 129999,
        imageUrl: 'https://images.unsplash.com/photo-1592899677977-9c10ca588bbd?auto=format&fit=crop&w=1000&q=85',
        isDefault: false,
        stockStatus: 'in_stock',
        emiLadder: [
          { tenureMonths: 12, annualInterestRate: 0, cashbackAmount: 7000, isRecommended: true },
          { tenureMonths: 24, annualInterestRate: 0, cashbackAmount: 7000, isRecommended: false },
        ],
      },
    ],
  },

  // ================= ONEPLUS =================
  {
    id: 7,
    slug: 'oneplus-13',
    name: 'OnePlus 13',
    brand: 'OnePlus',
    tagline: 'Snapdragon 8 Elite flagship with Hasselblad optical mastery & 6000mAh battery.',
    description: 'OnePlus flagship with Snapdragon 8 Elite, 2K Oriental display with DisplayMate A++, Hasselblad master camera system, and immense 6000mAh silicon-carbon battery with 100W SUPERVOOC charging.',
    category: 'flagship',
    rating: 4.82,
    reviewsCount: 290,
    specs: {
      display: '6.82-inch 2K LTPO AMOLED, 1-120Hz, 4500 nits peak, Dolby Vision',
      processor: 'Qualcomm Snapdragon 8 Elite (3nm)',
      camera: '50MP Sony LYT-808 OIS + 50MP Periscope 3x + 50MP Ultra-wide (Hasselblad tuned)',
      battery: '6000 mAh Glacier Battery, 100W wired + 50W wireless',
      os: 'OxygenOS 15 based on Android 15',
      security: 'Ultrasonic In-display Fingerprint',
      weight: '213g',
    },
    variants: [
      {
        id: 701,
        label: '256GB / Midnight Ocean',
        storage: '256GB',
        color: 'Midnight Ocean',
        colorHex: '#1E2A38',
        mrp: 69999,
        sellingPrice: 64999,
        imageUrl: 'https://images.unsplash.com/photo-1592286927505-1def25115df3?auto=format&fit=crop&w=1000&q=85',
        isDefault: true,
        stockStatus: 'in_stock',
        emiLadder: [
          { tenureMonths: 3, annualInterestRate: 0, cashbackAmount: 3000, isRecommended: false },
          { tenureMonths: 6, annualInterestRate: 0, cashbackAmount: 3000, isRecommended: false },
          { tenureMonths: 12, annualInterestRate: 0, cashbackAmount: 3000, isRecommended: true },
          { tenureMonths: 24, annualInterestRate: 0, cashbackAmount: 3000, isRecommended: false },
          { tenureMonths: 36, annualInterestRate: 10.5, cashbackAmount: 3000, isRecommended: false },
        ],
      },
      {
        id: 702,
        label: '256GB / Arctic Dawn',
        storage: '256GB',
        color: 'Arctic Dawn',
        colorHex: '#E7E4DD',
        mrp: 69999,
        sellingPrice: 65999,
        imageUrl: 'https://images.unsplash.com/photo-1567581935884-3349723552ca?auto=format&fit=crop&w=1000&q=85',
        isDefault: false,
        stockStatus: 'in_stock',
        emiLadder: [
          { tenureMonths: 6, annualInterestRate: 0, cashbackAmount: 3000, isRecommended: false },
          { tenureMonths: 12, annualInterestRate: 0, cashbackAmount: 3000, isRecommended: true },
          { tenureMonths: 24, annualInterestRate: 0, cashbackAmount: 3000, isRecommended: false },
        ],
      },
      {
        id: 703,
        label: '512GB / Midnight Ocean',
        storage: '512GB',
        color: 'Midnight Ocean',
        colorHex: '#1E2A38',
        mrp: 79999,
        sellingPrice: 74999,
        imageUrl: 'https://images.unsplash.com/photo-1592286927505-1def25115df3?auto=format&fit=crop&w=1000&q=85',
        isDefault: false,
        stockStatus: 'in_stock',
        emiLadder: [
          { tenureMonths: 6, annualInterestRate: 0, cashbackAmount: 3500, isRecommended: false },
          { tenureMonths: 12, annualInterestRate: 0, cashbackAmount: 3500, isRecommended: true },
          { tenureMonths: 24, annualInterestRate: 0, cashbackAmount: 3500, isRecommended: false },
        ],
      },
    ],
  },
  {
    id: 8,
    slug: 'oneplus-open',
    name: 'OnePlus Open',
    brand: 'OnePlus',
    tagline: 'Lightweight folding flagship with Hasselblad cameras & Open Canvas multi-window.',
    description: 'Thinnest inward folding smartphone with Flexion hinge, ProXDR 120Hz screens, Hasselblad triple cameras, and revolutionary Open Canvas multitasking UI.',
    category: 'foldable',
    rating: 4.86,
    reviewsCount: 165,
    specs: {
      display: 'Dual 120Hz ProXDR: 7.82" Interior (2800 nits) + 6.31" Exterior (2800 nits)',
      processor: 'Snapdragon 8 Gen 2 with 16GB LPDDR5X RAM',
      camera: '48MP LYT-T808 Pixel Stacked + 64MP 3x Periscope (6x in-sensor) + 48MP Ultra-wide',
      battery: '4805 mAh with 67W SUPERVOOC',
      os: 'OxygenOS 14 Open Edition',
      security: 'Side-mounted Fingerprint Scanner',
      weight: '239g',
    },
    variants: [
      {
        id: 801,
        label: '512GB / Emerald Dusk',
        storage: '512GB',
        color: 'Emerald Dusk',
        colorHex: '#254E41',
        mrp: 149999,
        sellingPrice: 139999,
        imageUrl: 'https://images.unsplash.com/photo-1541807084-5c52b6b3adef?auto=format&fit=crop&w=1000&q=85',
        isDefault: true,
        stockStatus: 'in_stock',
        emiLadder: [
          { tenureMonths: 6, annualInterestRate: 0, cashbackAmount: 7000, isRecommended: false },
          { tenureMonths: 12, annualInterestRate: 0, cashbackAmount: 7000, isRecommended: true },
          { tenureMonths: 24, annualInterestRate: 0, cashbackAmount: 7000, isRecommended: false },
          { tenureMonths: 36, annualInterestRate: 10.5, cashbackAmount: 7000, isRecommended: false },
        ],
      },
    ],
  },

  // ================= NOTHING =================
  {
    id: 9,
    slug: 'nothing-phone-2',
    name: 'Nothing Phone (2)',
    brand: 'Nothing',
    tagline: 'Iconic transparent Glyph Interface with clean Nothing OS 2.5.',
    description: 'Iconic transparent glass back with customizable LED Glyph lighting, Snapdragon 8+ Gen 1 flagship performance, 50MP Sony dual cameras, and bloatware-free Nothing OS.',
    category: 'flagship',
    rating: 4.75,
    reviewsCount: 210,
    specs: {
      display: '6.7-inch flexible LTPO OLED, 1-120Hz, 1600 nits peak',
      processor: 'Qualcomm Snapdragon 8+ Gen 1 (4nm)',
      camera: 'Dual 50MP Sony IMX890 Main + 50MP Samsung JN1 Ultra-wide',
      battery: '4700 mAh, 45W wired, 15W wireless, 5W reverse wireless',
      os: 'Nothing OS 2.6 on Android 14',
      security: 'Optical In-display Fingerprint',
      weight: '201g',
    },
    variants: [
      {
        id: 901,
        label: '256GB / Dark Gray',
        storage: '256GB',
        color: 'Dark Gray',
        colorHex: '#2D3139',
        mrp: 49999,
        sellingPrice: 37999,
        imageUrl: 'https://images.unsplash.com/photo-1598327105666-5b89351aff97?auto=format&fit=crop&w=1000&q=85',
        isDefault: true,
        stockStatus: 'in_stock',
        emiLadder: [
          { tenureMonths: 3, annualInterestRate: 0, cashbackAmount: 2000, isRecommended: false },
          { tenureMonths: 6, annualInterestRate: 0, cashbackAmount: 2000, isRecommended: false },
          { tenureMonths: 12, annualInterestRate: 0, cashbackAmount: 2000, isRecommended: true },
          { tenureMonths: 24, annualInterestRate: 0, cashbackAmount: 2000, isRecommended: false },
        ],
      },
      {
        id: 902,
        label: '512GB / White',
        storage: '512GB',
        color: 'White',
        colorHex: '#F3F4F6',
        mrp: 54999,
        sellingPrice: 42999,
        imageUrl: 'https://images.unsplash.com/photo-1580910051074-3eb694886505?auto=format&fit=crop&w=1000&q=85',
        isDefault: false,
        stockStatus: 'in_stock',
        emiLadder: [
          { tenureMonths: 6, annualInterestRate: 0, cashbackAmount: 2500, isRecommended: false },
          { tenureMonths: 12, annualInterestRate: 0, cashbackAmount: 2500, isRecommended: true },
          { tenureMonths: 24, annualInterestRate: 0, cashbackAmount: 2500, isRecommended: false },
        ],
      },
    ],
  },

  // ================= XIAOMI =================
  {
    id: 10,
    slug: 'xiaomi-14-ultra',
    name: 'Xiaomi 14 Ultra',
    brand: 'Xiaomi',
    tagline: 'Optical excellence co-engineered with Leica, featuring 1-inch sensor.',
    description: 'Leica Summilux all-focal length quad camera setup, custom 1-inch Sony LYT-900 sensor with stepless variable aperture (f/1.63-f/4.0), and Snapdragon 8 Gen 3 computing power.',
    category: 'flagship',
    rating: 4.84,
    reviewsCount: 145,
    specs: {
      display: '6.73-inch WQHD+ AMOLED, 1-120Hz LTPO, 3000 nits peak, Dolby Vision',
      processor: 'Snapdragon 8 Gen 3 with IceLoop liquid cooling',
      camera: 'Quad 50MP: 1-inch LYT-900 + 75mm Floating Telephoto + 120mm Periscope + 12mm Ultrawide',
      battery: '5000 mAh, 90W wired HyperCharge, 80W wireless HyperCharge',
      os: 'Xiaomi HyperOS',
      security: 'Ultrasonic In-display Fingerprint',
      weight: '219g',
    },
    variants: [
      {
        id: 1001,
        label: '512GB / Black Leica Vegan Leather',
        storage: '512GB',
        color: 'Black Leather',
        colorHex: '#18181B',
        mrp: 119999,
        sellingPrice: 99999,
        imageUrl: 'https://images.unsplash.com/photo-1511707171634-5f897ff02aa9?auto=format&fit=crop&w=1000&q=85',
        isDefault: true,
        stockStatus: 'in_stock',
        emiLadder: [
          { tenureMonths: 3, annualInterestRate: 0, cashbackAmount: 5000, isRecommended: false },
          { tenureMonths: 6, annualInterestRate: 0, cashbackAmount: 5000, isRecommended: false },
          { tenureMonths: 12, annualInterestRate: 0, cashbackAmount: 5000, isRecommended: true },
          { tenureMonths: 24, annualInterestRate: 0, cashbackAmount: 5000, isRecommended: false },
          { tenureMonths: 36, annualInterestRate: 10.5, cashbackAmount: 5000, isRecommended: false },
        ],
      },
      {
        id: 1002,
        label: '512GB / White Ceramic',
        storage: '512GB',
        color: 'White Ceramic',
        colorHex: '#E5E7EB',
        mrp: 119999,
        sellingPrice: 99999,
        imageUrl: 'https://images.unsplash.com/photo-1592899677977-9c10ca588bbd?auto=format&fit=crop&w=1000&q=85',
        isDefault: false,
        stockStatus: 'in_stock',
        emiLadder: [
          { tenureMonths: 6, annualInterestRate: 0, cashbackAmount: 5000, isRecommended: false },
          { tenureMonths: 12, annualInterestRate: 0, cashbackAmount: 5000, isRecommended: true },
          { tenureMonths: 24, annualInterestRate: 0, cashbackAmount: 5000, isRecommended: false },
        ],
      },
    ],
  },
];

module.exports = { PRODUCTS };
