/**
 * High-grade expanded smartphone catalog with authentic specs,
 * multiple variants, hex swatches, verified 4-angle image galleries,
 * and exact Apple company technical specifications.
 * Works seamlessly both standalone (embedded store) and in PostgreSQL.
 */

const PRODUCTS = [
  // ================= APPLE =================
  {
    id: 1,
    slug: 'iphone-16-pro-max',
    name: 'iPhone 16 Pro Max',
    brand: 'Apple',
    tagline: 'Hello, Apple Intelligence. Strong. Light. Pro.',
    description: "Apple's supreme flagship crafted in Grade 5 Titanium with thinner borders, expansive 6.9-inch Super Retina XDR display, A18 Pro chip, tactile Camera Control button, and 4K 120 fps Dolby Vision.",
    category: 'flagship',
    rating: 4.95,
    reviewsCount: 684,
    specs: {
      display: '6.9-inch Super Retina XDR OLED (2868x1320 at 460 ppi), ProMotion 120Hz, Always-On, Dynamic Island, 2,000 nits peak outdoor, Latest-gen Ceramic Shield',
      processor: 'Apple A18 Pro chip (second-gen 3nm) with 6-core CPU (2 performance & 4 efficiency), 6-core GPU with hardware ray tracing, 16-core Neural Engine',
      camera: 'Pro camera system: 48MP Fusion (24mm, ƒ/1.78, 2nd-gen sensor-shift OIS) + 48MP Ultra Wide (13mm, ƒ/2.2, 120° FOV, hybrid Focus Pixels) + 12MP 5x Telephoto (120mm, ƒ/2.8), Camera Control button with tactile haptic sensor, 4K 120 fps Dolby Vision, Studio-quality 4-mic array with Spatial Audio',
      battery: 'Built-in rechargeable lithium-ion, Up to 33 hours video playback (29 hours streamed), Fast-charge capable: up to 50% charge in around 30 mins with 20W+ adapter or 25W MagSafe',
      build: 'Grade 5 Titanium with textured matte glass back, Action button, Camera Control, IP68 rated (maximum depth of 6m up to 30 mins), 227 grams',
      os: 'iOS 18 with Apple Intelligence personal AI system',
      security: 'Face ID enabled by TrueDepth camera for secure authentication',
    },
    variants: [
      {
        id: 101,
        label: '256GB / Desert Titanium',
        storage: '256GB',
        color: 'Desert Titanium',
        colorHex: '#C5A880',
        mrp: 144900,
        sellingPrice: 144900,
        imageUrl: 'https://images.unsplash.com/photo-1695048133142-1a20484d2569?auto=format&fit=crop&w=1200&q=85',
        images: [
          {
            angle: 'front_back',
            label: 'Front & Back View',
            url: 'https://images.unsplash.com/photo-1695048133142-1a20484d2569?auto=format&fit=crop&w=1200&q=85',
            thumbUrl: 'https://images.unsplash.com/photo-1695048133142-1a20484d2569?auto=format&fit=crop&w=200&q=80',
          },
          {
            angle: 'camera',
            label: '48MP Fusion Camera Island',
            url: 'https://images.unsplash.com/photo-1695048132966-4b6c30f0e02b?auto=format&fit=crop&w=1200&q=85',
            thumbUrl: 'https://images.unsplash.com/photo-1695048132966-4b6c30f0e02b?auto=format&fit=crop&w=200&q=80',
          },
          {
            angle: 'side',
            label: 'Titanium Edge & Camera Control',
            url: 'https://images.unsplash.com/photo-1510557880182-3d4d3cba35a5?auto=format&fit=crop&w=1200&q=85',
            thumbUrl: 'https://images.unsplash.com/photo-1510557880182-3d4d3cba35a5?auto=format&fit=crop&w=200&q=80',
          },
          {
            angle: 'lineup',
            label: 'All Titanium Finishes',
            url: 'https://images.unsplash.com/photo-1592750475338-74b7b21085ab?auto=format&fit=crop&w=1200&q=85',
            thumbUrl: 'https://images.unsplash.com/photo-1592750475338-74b7b21085ab?auto=format&fit=crop&w=200&q=80',
          },
        ],
        isDefault: true,
        stockStatus: 'in_stock',
        emiLadder: [
          { tenureMonths: 3, annualInterestRate: 0, cashbackAmount: 8000, isRecommended: false },
          { tenureMonths: 6, annualInterestRate: 0, cashbackAmount: 8000, isRecommended: false },
          { tenureMonths: 12, annualInterestRate: 0, cashbackAmount: 8000, isRecommended: true },
          { tenureMonths: 24, annualInterestRate: 0, cashbackAmount: 8000, isRecommended: false },
          { tenureMonths: 36, annualInterestRate: 10.5, cashbackAmount: 8000, isRecommended: false },
          { tenureMonths: 48, annualInterestRate: 10.5, cashbackAmount: 8000, isRecommended: false },
        ],
      },
      {
        id: 102,
        label: '256GB / Natural Titanium',
        storage: '256GB',
        color: 'Natural Titanium',
        colorHex: '#9E978E',
        mrp: 144900,
        sellingPrice: 144900,
        imageUrl: 'https://images.unsplash.com/photo-1592750475338-74b7b21085ab?auto=format&fit=crop&w=1200&q=85',
        images: [
          {
            angle: 'front_back',
            label: 'Front & Back View',
            url: 'https://images.unsplash.com/photo-1592750475338-74b7b21085ab?auto=format&fit=crop&w=1200&q=85',
            thumbUrl: 'https://images.unsplash.com/photo-1592750475338-74b7b21085ab?auto=format&fit=crop&w=200&q=80',
          },
          {
            angle: 'camera',
            label: '48MP Fusion Camera Island',
            url: 'https://images.unsplash.com/photo-1695048132966-4b6c30f0e02b?auto=format&fit=crop&w=1200&q=85',
            thumbUrl: 'https://images.unsplash.com/photo-1695048132966-4b6c30f0e02b?auto=format&fit=crop&w=200&q=80',
          },
          {
            angle: 'side',
            label: 'Grade 5 Titanium Profile',
            url: 'https://images.unsplash.com/photo-1510557880182-3d4d3cba35a5?auto=format&fit=crop&w=1200&q=85',
            thumbUrl: 'https://images.unsplash.com/photo-1510557880182-3d4d3cba35a5?auto=format&fit=crop&w=200&q=80',
          },
          {
            angle: 'lineup',
            label: 'All Titanium Finishes',
            url: 'https://images.unsplash.com/photo-1695048133142-1a20484d2569?auto=format&fit=crop&w=1200&q=85',
            thumbUrl: 'https://images.unsplash.com/photo-1695048133142-1a20484d2569?auto=format&fit=crop&w=200&q=80',
          },
        ],
        isDefault: false,
        stockStatus: 'in_stock',
        emiLadder: [
          { tenureMonths: 6, annualInterestRate: 0, cashbackAmount: 8000, isRecommended: false },
          { tenureMonths: 12, annualInterestRate: 0, cashbackAmount: 8000, isRecommended: true },
          { tenureMonths: 24, annualInterestRate: 0, cashbackAmount: 8000, isRecommended: false },
        ],
      },
      {
        id: 103,
        label: '512GB / White Titanium',
        storage: '512GB',
        color: 'White Titanium',
        colorHex: '#F2F2F0',
        mrp: 164900,
        sellingPrice: 164900,
        imageUrl: 'https://images.unsplash.com/photo-1511707171634-5f897ff02aa9?auto=format&fit=crop&w=1200&q=85',
        images: [
          {
            angle: 'front_back',
            label: 'Front & Back View',
            url: 'https://images.unsplash.com/photo-1511707171634-5f897ff02aa9?auto=format&fit=crop&w=1200&q=85',
            thumbUrl: 'https://images.unsplash.com/photo-1511707171634-5f897ff02aa9?auto=format&fit=crop&w=200&q=80',
          },
          {
            angle: 'camera',
            label: '48MP Camera Detail',
            url: 'https://images.unsplash.com/photo-1695048132966-4b6c30f0e02b?auto=format&fit=crop&w=1200&q=85',
            thumbUrl: 'https://images.unsplash.com/photo-1695048132966-4b6c30f0e02b?auto=format&fit=crop&w=200&q=80',
          },
          {
            angle: 'side',
            label: 'Titanium Side Profile',
            url: 'https://images.unsplash.com/photo-1510557880182-3d4d3cba35a5?auto=format&fit=crop&w=1200&q=85',
            thumbUrl: 'https://images.unsplash.com/photo-1510557880182-3d4d3cba35a5?auto=format&fit=crop&w=200&q=80',
          },
        ],
        isDefault: false,
        stockStatus: 'in_stock',
        emiLadder: [
          { tenureMonths: 6, annualInterestRate: 0, cashbackAmount: 9000, isRecommended: false },
          { tenureMonths: 12, annualInterestRate: 0, cashbackAmount: 9000, isRecommended: true },
          { tenureMonths: 24, annualInterestRate: 0, cashbackAmount: 9000, isRecommended: false },
        ],
      },
      {
        id: 104,
        label: '1TB / Black Titanium',
        storage: '1TB',
        color: 'Black Titanium',
        colorHex: '#3B3A36',
        mrp: 184900,
        sellingPrice: 184900,
        imageUrl: 'https://images.unsplash.com/photo-1695048133142-1a20484d2569?auto=format&fit=crop&w=1200&q=85',
        images: [
          {
            angle: 'front_back',
            label: 'Front & Back View',
            url: 'https://images.unsplash.com/photo-1695048133142-1a20484d2569?auto=format&fit=crop&w=1200&q=85',
          },
          {
            angle: 'camera',
            label: 'Camera Array Closeup',
            url: 'https://images.unsplash.com/photo-1695048132966-4b6c30f0e02b?auto=format&fit=crop&w=1200&q=85',
          },
          {
            angle: 'side',
            label: 'Edge & Antenna Bands',
            url: 'https://images.unsplash.com/photo-1510557880182-3d4d3cba35a5?auto=format&fit=crop&w=1200&q=85',
          },
        ],
        isDefault: false,
        stockStatus: 'in_stock',
        emiLadder: [
          { tenureMonths: 12, annualInterestRate: 0, cashbackAmount: 10000, isRecommended: true },
          { tenureMonths: 24, annualInterestRate: 0, cashbackAmount: 10000, isRecommended: false },
        ],
      },
    ],
  },

  {
    id: 2,
    slug: 'iphone-16-pro',
    name: 'iPhone 16 Pro',
    brand: 'Apple',
    tagline: 'Pro performance in a versatile 6.3-inch titanium design.',
    description: "Powered by the breakthrough A18 Pro chip with 6-core GPU, stunning 6.3-inch Super Retina XDR display with ProMotion 120Hz, Camera Control, and 5x Telephoto optical zoom.",
    category: 'flagship',
    rating: 4.93,
    reviewsCount: 520,
    specs: {
      display: '6.3-inch Super Retina XDR OLED (2622x1206 at 460 ppi), ProMotion 120Hz, Always-On, Dynamic Island, 2,000 nits peak outdoor, Latest-gen Ceramic Shield',
      processor: 'Apple A18 Pro chip (3nm) with 6-core CPU, 6-core GPU, 16-core Neural Engine',
      camera: 'Pro camera system: 48MP Fusion (24mm, ƒ/1.78, sensor-shift OIS) + 48MP Ultra Wide (13mm, ƒ/2.2, Macro) + 12MP 5x Telephoto (120mm, ƒ/2.8), Camera Control, 4K 120 fps Dolby Vision',
      battery: 'Up to 27 hours video playback, Fast-charge 50% in 30 mins with 20W+ or 25W MagSafe',
      build: 'Grade 5 Titanium, textured matte glass back, Action button, Camera Control, IP68 water resistance, 199 grams',
      os: 'iOS 18 with Apple Intelligence',
      security: 'Face ID biometric authentication',
    },
    variants: [
      {
        id: 201,
        label: '128GB / Desert Titanium',
        storage: '128GB',
        color: 'Desert Titanium',
        colorHex: '#C5A880',
        mrp: 119900,
        sellingPrice: 119900,
        imageUrl: 'https://images.unsplash.com/photo-1695048133142-1a20484d2569?auto=format&fit=crop&w=1200&q=85',
        images: [
          {
            angle: 'front_back',
            label: 'Front & Back View',
            url: 'https://images.unsplash.com/photo-1695048133142-1a20484d2569?auto=format&fit=crop&w=1200&q=85',
          },
          {
            angle: 'camera',
            label: '48MP Triple Lens Cluster',
            url: 'https://images.unsplash.com/photo-1695048132966-4b6c30f0e02b?auto=format&fit=crop&w=1200&q=85',
          },
          {
            angle: 'side',
            label: 'Camera Control Button Profile',
            url: 'https://images.unsplash.com/photo-1510557880182-3d4d3cba35a5?auto=format&fit=crop&w=1200&q=85',
          },
          {
            angle: 'lineup',
            label: 'Titanium Finishes Lineup',
            url: 'https://images.unsplash.com/photo-1592750475338-74b7b21085ab?auto=format&fit=crop&w=1200&q=85',
          },
        ],
        isDefault: true,
        stockStatus: 'in_stock',
        emiLadder: [
          { tenureMonths: 3, annualInterestRate: 0, cashbackAmount: 7000, isRecommended: false },
          { tenureMonths: 6, annualInterestRate: 0, cashbackAmount: 7000, isRecommended: false },
          { tenureMonths: 12, annualInterestRate: 0, cashbackAmount: 7000, isRecommended: true },
          { tenureMonths: 24, annualInterestRate: 0, cashbackAmount: 7000, isRecommended: false },
        ],
      },
      {
        id: 202,
        label: '256GB / Natural Titanium',
        storage: '256GB',
        color: 'Natural Titanium',
        colorHex: '#9E978E',
        mrp: 129900,
        sellingPrice: 129900,
        imageUrl: 'https://images.unsplash.com/photo-1592750475338-74b7b21085ab?auto=format&fit=crop&w=1200&q=85',
        images: [
          {
            angle: 'front_back',
            label: 'Front & Back View',
            url: 'https://images.unsplash.com/photo-1592750475338-74b7b21085ab?auto=format&fit=crop&w=1200&q=85',
          },
          {
            angle: 'camera',
            label: 'Camera Island Closeup',
            url: 'https://images.unsplash.com/photo-1695048132966-4b6c30f0e02b?auto=format&fit=crop&w=1200&q=85',
          },
          {
            angle: 'side',
            label: 'Titanium Edge Profile',
            url: 'https://images.unsplash.com/photo-1510557880182-3d4d3cba35a5?auto=format&fit=crop&w=1200&q=85',
          },
        ],
        isDefault: false,
        stockStatus: 'in_stock',
        emiLadder: [
          { tenureMonths: 6, annualInterestRate: 0, cashbackAmount: 7500, isRecommended: false },
          { tenureMonths: 12, annualInterestRate: 0, cashbackAmount: 7500, isRecommended: true },
          { tenureMonths: 24, annualInterestRate: 0, cashbackAmount: 7500, isRecommended: false },
        ],
      },
      {
        id: 203,
        label: '512GB / Black Titanium',
        storage: '512GB',
        color: 'Black Titanium',
        colorHex: '#3B3A36',
        mrp: 149900,
        sellingPrice: 149900,
        imageUrl: 'https://images.unsplash.com/photo-1511707171634-5f897ff02aa9?auto=format&fit=crop&w=1200&q=85',
        images: [
          {
            angle: 'front_back',
            label: 'Front & Back View',
            url: 'https://images.unsplash.com/photo-1511707171634-5f897ff02aa9?auto=format&fit=crop&w=1200&q=85',
          },
          {
            angle: 'camera',
            label: 'Camera Detail View',
            url: 'https://images.unsplash.com/photo-1695048132966-4b6c30f0e02b?auto=format&fit=crop&w=1200&q=85',
          },
        ],
        isDefault: false,
        stockStatus: 'in_stock',
        emiLadder: [
          { tenureMonths: 12, annualInterestRate: 0, cashbackAmount: 8500, isRecommended: true },
          { tenureMonths: 24, annualInterestRate: 0, cashbackAmount: 8500, isRecommended: false },
        ],
      },
    ],
  },

  {
    id: 3,
    slug: 'iphone-16',
    name: 'iPhone 16',
    brand: 'Apple',
    tagline: 'Colour-infused glass with A18 chip and Camera Control.',
    description: "Built for Apple Intelligence with the all-new A18 processor, Camera Control, 48MP Fusion camera with 2x Telephoto optical quality, and Macro photography.",
    category: 'flagship',
    rating: 4.88,
    reviewsCount: 410,
    specs: {
      display: '6.1-inch Super Retina XDR OLED (2556x1179 at 460 ppi), Dynamic Island, 2,000 nits peak outdoor, Ceramic Shield front',
      processor: 'Apple A18 chip (3nm) with 6-core CPU, 5-core GPU, 16-core Neural Engine',
      camera: 'Advanced dual-camera: 48MP Fusion (26mm, ƒ/1.6, sensor-shift OIS, 2x Telephoto) + 12MP Ultra Wide with Macro, Camera Control, Spatial Photo & Video',
      battery: 'Up to 22 hours video playback, 25W MagSafe wireless charging',
      build: 'Aerospace-grade aluminium with colour-infused glass back, Action button, Camera Control, IP68 rated, 170 grams',
      os: 'iOS 18 with Apple Intelligence',
      security: 'Face ID',
    },
    variants: [
      {
        id: 301,
        label: '128GB / Ultramarine',
        storage: '128GB',
        color: 'Ultramarine',
        colorHex: '#4B6B94',
        mrp: 79900,
        sellingPrice: 79900,
        imageUrl: 'https://images.unsplash.com/photo-1591337676887-a217a6970a8a?auto=format&fit=crop&w=1200&q=85',
        images: [
          {
            angle: 'front_back',
            label: 'Front & Back View',
            url: 'https://images.unsplash.com/photo-1591337676887-a217a6970a8a?auto=format&fit=crop&w=1200&q=85',
          },
          {
            angle: 'camera',
            label: 'Vertical Dual Camera Island',
            url: 'https://images.unsplash.com/photo-1575695342320-d2d2d2f9b73f?auto=format&fit=crop&w=1200&q=85',
          },
          {
            angle: 'side',
            label: 'Colour-Infused Matte Edge',
            url: 'https://images.unsplash.com/photo-1510557880182-3d4d3cba35a5?auto=format&fit=crop&w=1200&q=85',
          },
        ],
        isDefault: true,
        stockStatus: 'in_stock',
        emiLadder: [
          { tenureMonths: 3, annualInterestRate: 0, cashbackAmount: 5000, isRecommended: false },
          { tenureMonths: 6, annualInterestRate: 0, cashbackAmount: 5000, isRecommended: false },
          { tenureMonths: 12, annualInterestRate: 0, cashbackAmount: 5000, isRecommended: true },
          { tenureMonths: 24, annualInterestRate: 0, cashbackAmount: 5000, isRecommended: false },
        ],
      },
      {
        id: 302,
        label: '256GB / Teal',
        storage: '256GB',
        color: 'Teal',
        colorHex: '#7BA89E',
        mrp: 89900,
        sellingPrice: 89900,
        imageUrl: 'https://images.unsplash.com/photo-1575695342320-d2d2d2f9b73f?auto=format&fit=crop&w=1200&q=85',
        images: [
          {
            angle: 'front_back',
            label: 'Front & Back View',
            url: 'https://images.unsplash.com/photo-1575695342320-d2d2d2f9b73f?auto=format&fit=crop&w=1200&q=85',
          },
          {
            angle: 'camera',
            label: 'Macro Dual Camera',
            url: 'https://images.unsplash.com/photo-1591337676887-a217a6970a8a?auto=format&fit=crop&w=1200&q=85',
          },
        ],
        isDefault: false,
        stockStatus: 'in_stock',
        emiLadder: [
          { tenureMonths: 6, annualInterestRate: 0, cashbackAmount: 5500, isRecommended: false },
          { tenureMonths: 12, annualInterestRate: 0, cashbackAmount: 5500, isRecommended: true },
          { tenureMonths: 24, annualInterestRate: 0, cashbackAmount: 5500, isRecommended: false },
        ],
      },
    ],
  },

  {
    id: 4,
    slug: 'iphone-16-plus',
    name: 'iPhone 16 Plus',
    brand: 'Apple',
    tagline: 'Expansive 6.7-inch display with stellar all-day battery life.',
    description: 'Bigger 6.7-inch Super Retina XDR screen, A18 bionic brain, Camera Control, 48MP Fusion camera with 2x Telephoto, and up to 27 hours battery.',
    category: 'flagship',
    rating: 4.86,
    reviewsCount: 290,
    specs: {
      display: '6.7-inch Super Retina XDR OLED (2796x1290 at 460 ppi), Dynamic Island, 2,000 nits peak outdoor',
      processor: 'Apple A18 chip (3nm) with Apple Intelligence',
      camera: '48MP Fusion + 12MP Ultra Wide with Macro, Camera Control, 4K Dolby Vision',
      battery: 'Up to 27 hours video playback, 25W MagSafe wireless',
      build: 'Aerospace-grade aluminium, colour-infused back glass, IP68 rated, 199 grams',
      os: 'iOS 18 with Apple Intelligence',
      security: 'Face ID',
    },
    variants: [
      {
        id: 401,
        label: '128GB / Ultramarine',
        storage: '128GB',
        color: 'Ultramarine',
        colorHex: '#4B6B94',
        mrp: 89900,
        sellingPrice: 89900,
        imageUrl: 'https://images.unsplash.com/photo-1591337676887-a217a6970a8a?auto=format&fit=crop&w=1200&q=85',
        images: [
          {
            angle: 'front_back',
            label: 'Front & Back View',
            url: 'https://images.unsplash.com/photo-1591337676887-a217a6970a8a?auto=format&fit=crop&w=1200&q=85',
          },
          {
            angle: 'camera',
            label: 'Dual Camera Assembly',
            url: 'https://images.unsplash.com/photo-1575695342320-d2d2d2f9b73f?auto=format&fit=crop&w=1200&q=85',
          },
        ],
        isDefault: true,
        stockStatus: 'in_stock',
        emiLadder: [
          { tenureMonths: 6, annualInterestRate: 0, cashbackAmount: 6000, isRecommended: false },
          { tenureMonths: 12, annualInterestRate: 0, cashbackAmount: 6000, isRecommended: true },
          { tenureMonths: 24, annualInterestRate: 0, cashbackAmount: 6000, isRecommended: false },
        ],
      },
    ],
  },

  {
    id: 5,
    slug: 'iphone-15-pro-max',
    name: 'iPhone 15 Pro Max',
    brand: 'Apple',
    tagline: 'Titanium powerhouse with A17 Pro and 5x optical telephoto.',
    description: "The groundbreaking Grade 5 titanium iPhone featuring the 3nm A17 Pro chip with console gaming support, customizable Action button, 48MP main sensor, and 5x tetraprism optical zoom.",
    category: 'flagship',
    rating: 4.91,
    reviewsCount: 820,
    specs: {
      display: '6.7-inch Super Retina XDR OLED (2796x1290 at 460 ppi), ProMotion 120Hz, Always-On, Dynamic Island, 2,000 nits peak',
      processor: 'Apple A17 Pro (3nm) with 6-core GPU & hardware ray tracing',
      camera: '48MP Main (24mm, ƒ/1.78, sensor-shift OIS) + 12MP Ultra Wide + 12MP 5x Telephoto (120mm), USB 3.0 up to 10Gb/s',
      battery: 'Up to 29 hours video playback',
      build: 'Titanium design with textured matte glass back, Action button, IP68 rated, 221 grams',
      os: 'iOS 18 upgradable',
      security: 'Face ID',
    },
    variants: [
      {
        id: 501,
        label: '256GB / Natural Titanium',
        storage: '256GB',
        color: 'Natural Titanium',
        colorHex: '#9E978E',
        mrp: 149900,
        sellingPrice: 134900,
        imageUrl: 'https://images.unsplash.com/photo-1592750475338-74b7b21085ab?auto=format&fit=crop&w=1200&q=85',
        images: [
          {
            angle: 'front_back',
            label: 'Front & Back View',
            url: 'https://images.unsplash.com/photo-1592750475338-74b7b21085ab?auto=format&fit=crop&w=1200&q=85',
          },
          {
            angle: 'camera',
            label: 'Triple Camera Array',
            url: 'https://images.unsplash.com/photo-1695048132966-4b6c30f0e02b?auto=format&fit=crop&w=1200&q=85',
          },
          {
            angle: 'side',
            label: 'Brushed Titanium Edge',
            url: 'https://images.unsplash.com/photo-1510557880182-3d4d3cba35a5?auto=format&fit=crop&w=1200&q=85',
          },
        ],
        isDefault: true,
        stockStatus: 'in_stock',
        emiLadder: [
          { tenureMonths: 6, annualInterestRate: 0, cashbackAmount: 7000, isRecommended: false },
          { tenureMonths: 12, annualInterestRate: 0, cashbackAmount: 7000, isRecommended: true },
          { tenureMonths: 24, annualInterestRate: 0, cashbackAmount: 7000, isRecommended: false },
        ],
      },
    ],
  },

  // ================= SAMSUNG =================
  {
    id: 6,
    slug: 'samsung-galaxy-s24-ultra',
    name: 'Galaxy S24 Ultra',
    brand: 'Samsung',
    tagline: 'Galaxy AI is here with built-in S-Pen and titanium armor.',
    description: 'Titanium frame, flat 6.8-inch Dynamic AMOLED 2X, Snapdragon 8 Gen 3 for Galaxy, quad telephoto with 200MP sensor, and Circle to Search.',
    category: 'flagship',
    rating: 4.9,
    reviewsCount: 460,
    specs: {
      display: '6.8-inch Dynamic AMOLED 2X, QHD+, 1-120Hz, 2600 nits peak, Corning Gorilla Armor anti-reflective',
      processor: 'Snapdragon 8 Gen 3 for Galaxy (4nm) with vapor chamber cooling',
      camera: '200MP Main (OIS) + 50MP 5x Periscope (10x optical-quality) + 10MP 3x Telephoto + 12MP Ultra-Wide',
      battery: '5000 mAh, 45W super-fast wired, 15W wireless',
      build: 'Titanium frame, integrated Bluetooth S-Pen stylus, IP68 rated, 232g',
      os: 'One UI 6.1 with 7 years of OS & security updates',
    },
    variants: [
      {
        id: 601,
        label: '256GB / Titanium Gray',
        storage: '256GB',
        color: 'Titanium Gray',
        colorHex: '#6B7280',
        mrp: 134999,
        sellingPrice: 129999,
        imageUrl: 'https://images.unsplash.com/photo-1610945415295-d9bbf067e59c?auto=format&fit=crop&w=1200&q=85',
        images: [
          {
            angle: 'front_back',
            label: 'Front & Integrated S-Pen View',
            url: 'https://images.unsplash.com/photo-1610945415295-d9bbf067e59c?auto=format&fit=crop&w=1200&q=85',
          },
          {
            angle: 'camera',
            label: '200MP Quad Telephoto Camera Array',
            url: 'https://images.unsplash.com/photo-1580910051074-3eb694886505?auto=format&fit=crop&w=1200&q=85',
          },
          {
            angle: 'side',
            label: 'Titanium Frame & S-Pen Silo',
            url: 'https://images.unsplash.com/photo-1511707171634-5f897ff02aa9?auto=format&fit=crop&w=1200&q=85',
          },
        ],
        isDefault: true,
        stockStatus: 'in_stock',
        emiLadder: [
          { tenureMonths: 6, annualInterestRate: 0, cashbackAmount: 7500, isRecommended: false },
          { tenureMonths: 12, annualInterestRate: 0, cashbackAmount: 7500, isRecommended: true },
          { tenureMonths: 24, annualInterestRate: 0, cashbackAmount: 7500, isRecommended: false },
        ],
      },
    ],
  },

  // ================= GOOGLE PIXEL =================
  {
    id: 7,
    slug: 'google-pixel-9-pro-xl',
    name: 'Pixel 9 Pro XL',
    brand: 'Google',
    tagline: 'Google Tensor G4 engineered with Gemini Pro AI.',
    description: 'The pinnacle of computational photography with iconic camera bar, Tensor G4, Super Actua display, and Gemini Live.',
    category: 'flagship',
    rating: 4.88,
    reviewsCount: 310,
    specs: {
      display: '6.8-inch Super Actua LTPO OLED, 1-120Hz, 3000 nits peak, Gorilla Glass Victus 2',
      processor: 'Google Tensor G4 (4nm) with Titan M2 security coprocessor',
      camera: '50MP Octa PD Main + 48MP Quad PD Ultra-Wide + 48MP Quad PD 5x Telephoto with 30x Super Res Zoom',
      battery: '5060 mAh, 37W wired, fast Qi-certified wireless',
      build: 'Polished metal frame with satin matte glass back, IP68 rated, 221g',
      os: 'Android 15 with 7 years of Pixel Drops & OS updates',
    },
    variants: [
      {
        id: 701,
        label: '256GB / Porcelain',
        storage: '256GB',
        color: 'Porcelain',
        colorHex: '#ECE7E1',
        mrp: 124999,
        sellingPrice: 124999,
        imageUrl: 'https://images.unsplash.com/photo-1598327105666-5b89351aff97?auto=format&fit=crop&w=1200&q=85',
        images: [
          {
            angle: 'front_back',
            label: 'Front & Iconic Camera Bar View',
            url: 'https://images.unsplash.com/photo-1598327105666-5b89351aff97?auto=format&fit=crop&w=1200&q=85',
          },
          {
            angle: 'camera',
            label: 'Sculpted Camera Visor Detail',
            url: 'https://images.unsplash.com/photo-1580910051074-3eb694886505?auto=format&fit=crop&w=1200&q=85',
          },
        ],
        isDefault: true,
        stockStatus: 'in_stock',
        emiLadder: [
          { tenureMonths: 6, annualInterestRate: 0, cashbackAmount: 7000, isRecommended: false },
          { tenureMonths: 12, annualInterestRate: 0, cashbackAmount: 7000, isRecommended: true },
          { tenureMonths: 24, annualInterestRate: 0, cashbackAmount: 7000, isRecommended: false },
        ],
      },
    ],
  },

  // ================= ONEPLUS =================
  {
    id: 8,
    slug: 'oneplus-13',
    name: 'OnePlus 13',
    brand: 'OnePlus',
    tagline: 'Extreme performance with Snapdragon 8 Elite & Hasselblad.',
    description: 'Industry-first 2K Oriental Display with DisplayMate A++ rating, massive 6000 mAh Glacier battery, and Hasselblad Master camera system.',
    category: 'flagship',
    rating: 4.87,
    reviewsCount: 390,
    specs: {
      display: '6.82-inch 2K LTPO AMOLED, 120Hz, 4500 nits peak, Glove & Rain touch support',
      processor: 'Qualcomm Snapdragon 8 Elite (3nm, Oryon CPU up to 4.32 GHz)',
      camera: 'Triple 50MP Sony LYT-808 Main + 50MP Ultra-Wide + 50MP 3x Periscope Telephoto (Hasselblad tuned)',
      battery: '6000 mAh Glacier Silicon-Carbon battery, 100W SuperVOOC, 50W wireless',
      build: 'Ceramic & glass composite, IP68 + IP69 rated, 213g',
      os: 'OxygenOS 15 based on Android 15',
    },
    variants: [
      {
        id: 801,
        label: '256GB / Midnight Black',
        storage: '256GB',
        color: 'Midnight Black',
        colorHex: '#181A1B',
        mrp: 69999,
        sellingPrice: 69999,
        imageUrl: 'https://images.unsplash.com/photo-1565849904461-04a58ad377e0?auto=format&fit=crop&w=1200&q=85',
        images: [
          {
            angle: 'front_back',
            label: 'Front & Circular Camera Dial View',
            url: 'https://images.unsplash.com/photo-1565849904461-04a58ad377e0?auto=format&fit=crop&w=1200&q=85',
          },
          {
            angle: 'camera',
            label: 'Hasselblad Triple 50MP Lens Detail',
            url: 'https://images.unsplash.com/photo-1580910051074-3eb694886505?auto=format&fit=crop&w=1200&q=85',
          },
        ],
        isDefault: true,
        stockStatus: 'in_stock',
        emiLadder: [
          { tenureMonths: 6, annualInterestRate: 0, cashbackAmount: 4000, isRecommended: false },
          { tenureMonths: 12, annualInterestRate: 0, cashbackAmount: 4000, isRecommended: true },
          { tenureMonths: 24, annualInterestRate: 0, cashbackAmount: 4000, isRecommended: false },
        ],
      },
    ],
  },
];

module.exports = { PRODUCTS };
